"""Initial migration.

Revision ID: 1dd16c3ccb6c
Revises: 225578046c91
Create Date: 2024-02-02 16:15:39.466353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd16c3ccb6c'
down_revision = '225578046c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_content', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
