"""Initial migration.

Revision ID: 225578046c91
Revises: 079df2912c1f
Create Date: 2024-02-02 15:45:31.453987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225578046c91'
down_revision = '079df2912c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_content',
    sa.Column('playlist_content_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.playlist_id'], ),
    sa.PrimaryKeyConstraint('playlist_content_id')
    )
    with op.batch_alter_table('playlist_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playlist_content_playlist_content_id'), ['playlist_content_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playlist_content_playlist_content_id'))

    op.drop_table('playlist_content')
    # ### end Alembic commands ###
