"""Initial migration.

Revision ID: 83938efe0f85
Revises: d2962a31cb6e
Create Date: 2024-02-02 15:39:42.438972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83938efe0f85'
down_revision = 'd2962a31cb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
