"""Addede timestamp

Revision ID: a648c698674c
Revises: c16a084fd871
Create Date: 2024-02-04 13:23:39.470979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a648c698674c'
down_revision = 'c16a084fd871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_content', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
