"""Initial migration.

Revision ID: b311dfff34ad
Revises: f8e1c09a649e
Create Date: 2024-02-02 20:44:46.241980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b311dfff34ad'
down_revision = 'f8e1c09a649e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_playlists', schema=None) as batch_op:
        batch_op.alter_column('shared_with_user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('shared_with_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shared_with_user_id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('shared_with_user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
