"""Initial migration.

Revision ID: b33af8863735
Revises: d04d225f5e35
Create Date: 2024-02-02 20:12:30.570964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33af8863735'
down_revision = 'd04d225f5e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_content', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_playlist_content', ['playlist_id', 'track_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_content', schema=None) as batch_op:
        batch_op.drop_constraint('unique_playlist_content', type_='unique')

    # ### end Alembic commands ###
