"""Initial migration.

Revision ID: d04d225f5e35
Revises: e814151cf935
Create Date: 2024-02-02 19:22:13.555570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04d225f5e35'
down_revision = 'e814151cf935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_content', schema=None) as batch_op:
        batch_op.alter_column('track_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('track_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
