"""Initial migration.

Revision ID: e25c18df002c
Revises: 83938efe0f85
Create Date: 2024-02-02 15:41:14.788518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25c18df002c'
down_revision = '83938efe0f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('playlist_description', sa.String(), nullable=True))
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('playlist_description')
        batch_op.drop_column('playlist_name')

    # ### end Alembic commands ###
