"""Initial migration.

Revision ID: e814151cf935
Revises: 1dd16c3ccb6c
Create Date: 2024-02-02 18:12:49.229183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e814151cf935'
down_revision = '1dd16c3ccb6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_playlists',
    sa.Column('shared_playlist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.playlist_id'], ),
    sa.PrimaryKeyConstraint('shared_playlist_id')
    )
    with op.batch_alter_table('shared_playlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_playlists_shared_playlist_id'), ['shared_playlist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shared_playlists_shared_playlist_id'))

    op.drop_table('shared_playlists')
    # ### end Alembic commands ###
