"""Initial migration.

Revision ID: f8e1c09a649e
Revises: b33af8863735
Create Date: 2024-02-02 20:20:11.933653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e1c09a649e'
down_revision = 'b33af8863735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_playlists', schema=None) as batch_op:
        batch_op.alter_column('shared_with_user_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_playlists', schema=None) as batch_op:
        batch_op.alter_column('shared_with_user_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
