"""Initial migration.

Revision ID: fe72f5e217d7
Revises: b311dfff34ad
Create Date: 2024-02-02 21:09:23.236416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe72f5e217d7'
down_revision = 'b311dfff34ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_playlists', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_shared_playlist', ['playlist_id', 'shared_with_user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_playlists', schema=None) as batch_op:
        batch_op.drop_constraint('unique_shared_playlist', type_='unique')

    # ### end Alembic commands ###
