"""Second migration123123.

Revision ID: 709da38e76ee
Revises: 9b7d6d4f64f7
Create Date: 2024-01-06 15:30:47.379175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709da38e76ee'
down_revision = '9b7d6d4f64f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
