"""Second migration123123.

Revision ID: 9b7d6d4f64f7
Revises: bf8ee91e96eb
Create Date: 2024-01-06 14:52:45.422659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7d6d4f64f7'
down_revision = 'bf8ee91e96eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=32), nullable=True))
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('lname', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
