"""Initial migration.asdasdas

Revision ID: 053b9703287d
Revises: 1638fe0299f4
Create Date: 2024-01-07 23:47:20.695349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053b9703287d'
down_revision = '1638fe0299f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_friendship', ['user_id', 'friend_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_constraint('unique_friendship', type_='unique')

    # ### end Alembic commands ###
