"""Second migration123.

Revision ID: 453c88988fbf
Revises: e940ab7bfc20
Create Date: 2024-01-06 12:28:43.233003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453c88988fbf'
down_revision = 'e940ab7bfc20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lname', sa.String(length=32), nullable=True),
    sa.Column('fname', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
