"""Second migration123123.

Revision ID: bf8ee91e96eb
Revises: be07bc9049fa
Create Date: 2024-01-06 14:52:05.250655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8ee91e96eb'
down_revision = 'be07bc9049fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=32), nullable=True))

    # ### end Alembic commands ###
